import './globals.css'
import Navbar from './components/ui/navbar/Navbar'

export const metadata = {
  title: 'HAYAMA せた亭',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <head>
        <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet" />

      </head>

      <body className='min-h-screen flex flex-col font-EB-garamond text-slate-700 text-[16px] overflow-x-hidden'>

        <Navbar />
        <div className='pt-[50px] lg:pt-[150px]'>
          {children}
        </div>

      </body>
    </html>
  )
}
